-- Schema: net_archives.db
-- Generated: 2026-06-04

CREATE TABLE sessions (
    session_id      INTEGER PRIMARY KEY AUTOINCREMENT,
    freq_type       TEXT,
    net_name        TEXT,
    net_date        TEXT,
    start_time      TEXT,
    transceiver     TEXT,
    antenna         TEXT,
    location        TEXT,
    primary_freq    TEXT,
    alt_freq_1      TEXT,
    alt_freq_2      TEXT,
    digital_mode    TEXT,
    secured_time    TEXT,
    propagation     TEXT,
    noise_level     TEXT,
    antenna_1_desc  TEXT,
    antenna_2_desc  TEXT,
    ncs_callsign    TEXT,
    show_my_db      INTEGER DEFAULT 0,
    manual_time     INTEGER DEFAULT 0,
    archived_at     TEXT
);

CREATE TABLE checkins (
    checkin_id          INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id          INTEGER NOT NULL,
    freq_type           TEXT,
    from_callsign       TEXT,
    to_callsign         TEXT,
    checkin_time        TEXT,
    manual_time         INTEGER DEFAULT 0,
    noise_level         TEXT,
    antenna             TEXT,
    signal_L            INTEGER DEFAULT 0,
    signal_G            INTEGER DEFAULT 0,
    signal_W            INTEGER DEFAULT 0,
    signal_VW           INTEGER DEFAULT 0,
    signal_F            INTEGER DEFAULT 0,
    signal_C            INTEGER DEFAULT 0,
    signal_R            INTEGER DEFAULT 0,
    signal_UR           INTEGER DEFAULT 0,
    signal_D            INTEGER DEFAULT 0,
    signal_WI           INTEGER DEFAULT 0,
    signal_I            INTEGER DEFAULT 0,
    has_traffic         INTEGER DEFAULT 0,
    traffic_destination TEXT,
    traffic_notes       TEXT,
    propagation         TEXT,
    from_operator       TEXT,
    to_operator         TEXT,
    city                TEXT,
    state               TEXT,
    sector              TEXT,
    distance_miles      REAL,
    bearing_degrees     REAL,
    checkin_order       INTEGER,
    dest_operator       TEXT
);
